### PR TITLE
Added closed conference cfp

### PR DESCRIPTION
**Pull request by KathrynN**
Added additional section in readme.md for closed conference cfp deadlines, for easier parsing.

### CODE REVIEW

**Comment by mmatloka** [comment]
Hello, there is already a section `### Finished`, however I move CFPs there in batches every few weeks.

**Comment by KathrynN** [comment]
Ah, sorry, thought those were conferences which had actually been and gone.  Mind if I update to move these below the finished line?

**Comment by mmatloka** [comment]
I've moved them, done :) btw what type of parsing?

**Comment by KathrynN** [comment]
Mostly by my eyes!  :D

**Comment by mmatloka** [comment]
:D

**Pull request closed without merging**
